// -------------------------------------------------------------
// MolSpin input file generated by MOLSPIN_PYTHON
// -------------------------------------------------------------
SpinSystem GS
{
	// ---------------------------------------------------------
	// Spins
	// ---------------------------------------------------------
	Spin e1 
	{
		Spin = 1;
		type = electron;
		tensor = isotropic(2);
	}		
	Spin N14 
	{
		Spin = 1;
		type = nucleus;
		tensor = isotropic(1.0);
	}		
	// ---------------------------------------------------------
	// Interactions
	// ---------------------------------------------------------
	Interaction zfs
	{
		type = zfs;
		group1 = e1;
		dvalue = 0.1023696699;
		E = 0;
		prefactor = 0.5;
		energyshift = true;
	}
	Interaction E1N14
	{
		type = hyperfine;
		group1 = e1;
		group2 = N14;
		tensor = matrix("-2.70 0 0 ; 0 -2.70 0 ; 0 0 -2.14");
		prefactor = 0.035682426404996e-3;
	}
	Interaction N14nqp
	{
		type = zfs;
		group1 = N14;
		dvalue = -4.95;
		E = 0.0;
		prefactor = 6.283185306e-3;
		commonprefactor = false;
		energyshift = true;
	}
	Interaction zeeman
	{
		type = singlespin;
		spins = e1;
		field = "0.0 0.0 0.101";
	}
	Interaction nuclearzeeman
	{
		type = singlespin;
		spins = N14;
		field = "0.0 0.0 0.101";
		prefactor = -0.019327078;
		commonprefactor = false;
	}
	Interaction strain
	{
		type = strain;
		group1 = e1;
		E = "-4.0e-5 0.0 0.0 -4.0e-5 0.0 8.3e-4";
		D = "2.3 -6.42 -2.83 -2.6 19.66 5.7";
		prefactor = 0.035682426404996;
	}
	// ---------------------------------------------------------
	// Spin States
	// ---------------------------------------------------------
	State T0
	{
	    spin(e1) = |0>;
	}
	State TP
	{
	    spin(e1) = |1>;
	}
	State TD
	{
	    spin(e1) = |-1>;
	}
	State T0_U
	{
	    spin(e1) = |0>;
	    spin(N14) = |1>;
	}
	State T0_Z
	{
	    spin(e1) = |0>;
	    spin(N14) = |0>;
	}
	State T0_D
	{
	    spin(e1) = |0>;
	    spin(N14) = |-1>;
	}
	State TP_U
	{
	    spin(e1) = |1>;
	    spin(N14) = |1>;
	}
	State TP_Z
	{
	    spin(e1) = |1>;
	    spin(N14) = |0>;
	}
	State TP_D
	{
	    spin(e1) = |1>;
	    spin(N14) = |-1>;
	}
	State TD_U
	{
	    spin(e1) = |-1>;
	    spin(N14) = |1>;
	}
	State TD_Z
	{
	    spin(e1) = |-1>;
	    spin(N14) = |0>;
	}
	State TD_D
	{
	    spin(e1) = |-1>;
	    spin(N14) = |-1>;
	}
	State Identity
	{
	}
	// ---------------------------------------------------------
	// SpinSystem Properties
	// ---------------------------------------------------------
	Properties prop
	{
		initialstate = T0_U;
	}
	// ---------------------------------------------------------
	// SpinSystem Pulses
	// ---------------------------------------------------------
	Pulse pulsed_ODMR
	{
		type = LongPulse;
		field = "0.6315e-4 0.0 0.0";
		frequency = 0.0;
		pulsetime = 200.0;
		group = "e1, N14";
		prefactorlist = "1.0, 1.0, 1.0, -0.019327078, -0.019327078, -0.019327078";
		commonprefactorlist = "true, false";
		ignoretensorslist = "false, false";
		timestep = 0.5;
	}
	PulseSequence ODMR_sequence
	{
		tau1 = 1000.0;
		sequence = "pulsed_ODMR, tau1";
	}
}
Settings
{
	// ---------------------------------------------------------
	// General settings
	// ---------------------------------------------------------
	Settings general
	{
		steps = 401;
	}
	// ---------------------------------------------------------
	// Actions
	// ---------------------------------------------------------
	Action increasefieldstrength1
	{
		type = addvector;
		vector = GS.zeeman.field;
		direction = "0 0 1";
		value = 5e-6;
		period = 1;
	}
	Action increasefieldstrength2
	{
		type = addvector;
		vector = GS.nuclearzeeman.field;
		direction = "0 0 1";
		value = 5e-6;
		period = 1;
	}
	// ---------------------------------------------------------
	// Outputs
	// ---------------------------------------------------------
	Output fieldstrength
	{
		type = length;
		vector = GS.zeeman.field;
	}
	Output resonance_frequency
	{
		type = scalar;
		scalar = GS.pulsed_ODMR.frequency;
	}
}
Run
{
	Task TE
	{
		type = multistaticss-timeevolution;
		logfile = "outputs/Sp-St-NV-ODMR/molspin_results/Sp-St-NV-ODMR-TE-0.log";
		datafile = "outputs/Sp-St-NV-ODMR/molspin_results/Sp-St-NV-ODMR-TE-0.dat";
		ReactionOperator = Haberkorn;
		transitionyields = false;
		timestep = 0.1;
		totaltime = 200;
		minimumtimestep = 0.01;
		maximumtimestep = 5;
		atol = 1e-8;
		rtol = 1e-10;
	}
}