// -------------------------------------------------------------
// MolSpin input file generated by MOLSPIN_PYTHON
// -------------------------------------------------------------
SpinSystem GS
{
	// ---------------------------------------------------------
	// Spins
	// ---------------------------------------------------------
	Spin e1 
	{
		Spin = 1;
		type = electron;
		tensor = isotropic(2);
	}		
	Spin N14 
	{
		Spin = 1;
		type = nucleus;
		tensor = isotropic(1.0);
	}		
	// ---------------------------------------------------------
	// Interactions
	// ---------------------------------------------------------
	Interaction zfs
	{
		type = zfs;
		group1 = e1;
		dvalue = 0.1023696699;
		E = 0;
		prefactor = 0.5;
		energyshift = true;
	}
	Interaction E1N14
	{
		type = hyperfine;
		group1 = e1;
		group2 = N14;
		tensor = matrix("-2.70 0 0 ; 0 -2.70 0 ; 0 0 -2.14");
		prefactor = 0.035682426404996e-3;
	}
	Interaction N14nqp
	{
		type = zfs;
		group1 = N14;
		dvalue = -5.01;
		E = 0.0;
		prefactor = 6.283185306e-3;
		commonprefactor = false;
		energyshift = true;
	}
	Interaction zeeman
	{
		type = singlespin;
		spins = e1;
		field = "0.0 0.0 0.0";
	}
	Interaction nuclearzeeman
	{
		type = singlespin;
		spins = N14;
		field = "0.0 0.0 0.0";
		prefactor = -0.019327078;
		commonprefactor = false;
	}
	Interaction strain
	{
		type = strain;
		group1 = e1;
		E = "1.e-05 1.e-05 1.e-05";
		D = "13.3 21.5 20";
		prefactor = 0.035682426404996;
	}
	Interaction strain_modulated
	{
		type = strain;
		group1 = e1;
		E = "5.e-06 5.e-06 5.e-06";
		D = "13.3 21.5 20";
		prefactor = 0.035682426404996;
		tensortype = broadband;
		minfreq = 0;
		maxfreq = 50;
		components = 50000;
		autoseed = true;
		rwdcoeff = 0.5;
	}
	// ---------------------------------------------------------
	// Spin States
	// ---------------------------------------------------------
	State T0
	{
	    spin(e1) = |0>;
	}
	State TP
	{
	    spin(e1) = |1>; 
	} 
	State TD 
	{ 
		spin(e1) = |-1>; 
	} 
	State T0_U 
	{ 
		spin(e1) = |0>;
	    spin(N14) = |1>;
	}
	State T0_Z
	{
	    spin(e1) = |0>;
	    spin(N14) = |0>;
	}
	State T0_D
	{
	    spin(e1) = |0>;
	    spin(N14) = |-1>;
	}
	State TP_U
	{
	    spin(e1) = |1>;
	    spin(N14) = |1>;
	}
	State TP_Z
	{
	    spin(e1) = |1>;
	    spin(N14) = |0>;
	}
	State TP_D
	{
	    spin(e1) = |1>;
	    spin(N14) = |-1>;
	}
	State TD_U
	{
	    spin(e1) = |-1>;
	    spin(N14) = |1>;
	}
	State TD_Z
	{
	    spin(e1) = |-1>;
	    spin(N14) = |0>;
	}
	State TD_D
	{
	    spin(e1) = |-1>;
	    spin(N14) = |-1>;
	}
	State Identity
	{
	}
	// ---------------------------------------------------------
	// Transitions
	// ---------------------------------------------------------
	Transition T0UP
	{
	    source = T0_U;
	    targetsystem = ES;
	    targetstate = T0_U;
	    rate = 0.01;
	}
	Transition T0ZP
	{
	    source = T0_Z;
	    targetsystem = ES;
	    targetstate = T0_Z;
	    rate = 0.01;
	}
	Transition T0DP
	{
	    source = T0_D;
	    targetsystem = ES;
	    targetstate = T0_D;
	    rate = 0.01;
	}
	Transition TPUP
	{
	    source = TP_U;
	    targetsystem = ES;
	    targetstate = TP_U;
	    rate = 0.01;
	}
	Transition TPZP
	{
	    source = TP_Z;
	    targetsystem = ES;
	    targetstate = TP_Z;
	    rate = 0.01;
	}
	Transition TPDP
	{
	    source = TP_D;
	    targetsystem = ES;
	    targetstate = TP_D;
	    rate = 0.01;
	}
	Transition TDUP
	{
	    source = TD_U;
	    targetsystem = ES;
	    targetstate = TD_U;
	    rate = 0.01;
	}
	Transition TDZP
	{
	    source = TD_Z;
	    targetsystem = ES;
	    targetstate = TD_Z;
	    rate = 0.01;
	}
	Transition TDDP
	{
	    source = TD_D;
	    targetsystem = ES;
	    targetstate = TD_D;
	    rate = 0.01;
	}
	// ---------------------------------------------------------
	// SpinSystem Properties
	// ---------------------------------------------------------
	Properties prop
	{
		initialstate = T0;
	}
}
SpinSystem ES
{
	// ---------------------------------------------------------
	// Spins
	// ---------------------------------------------------------
	Spin e1 
	{
		Spin = 1;
		type = electron;
		tensor = isotropic(2);
	}		
	Spin N14 
	{
		Spin = 1;
		type = nucleus;
		tensor = isotropic(1.0);
	}		
	// ---------------------------------------------------------
	// Interactions
	// ---------------------------------------------------------
	Interaction zfs
	{
		type = zfs;
		group1 = e1;
		dvalue = 1420;
		prefactor = 0.0178412132e-3;
		energyshift = true;
	}
	Interaction E1N14
	{
		type = hyperfine;
		group1 = e1;
		group2 = N14;
		tensor = matrix("40 0 0 ; 0 40 0 ; 0 0 -23");
		prefactor = 0.035682426404996e-3;
	}
	Interaction N14nqp
	{
		type = zfs;
		group1 = N14;
		dvalue = -5.01;
		prefactor = 6.283185306e-3;
		commonprefactor = false;
		energyshift = true;
	}
	Interaction zeeman
	{
		type = singlespin;
		spins = e1;
		field = "0.0 0.0 0.0";
	}
	Interaction nuclearzeeman
	{
		type = singlespin;
		spins = N14;
		field = "0.0 0.0 0.0";
		prefactor = -0.019327078;
		commonprefactor = false;
	}
	Interaction strain
	{
		type = strain;
		group1 = e1;
		E = "1e-5 1e-5 1e-5";
		D = "13.3 21.5 20";
		prefactor = 0.48171275646745;
	}
	Interaction strain_modulated
	{
		type = strain;
		group1 = e1;
		E = "5e-6 5e-6 5e-6";
		D = "13.3 21.5 20";
		prefactor = 0.48171275646745;
		tensortype = broadband;
		minfreq = 0;
		maxfreq = 50;
		components = 50000;
		autoseed = true;
		rwdcoeff = 0.5;
	}
	// ---------------------------------------------------------
	// Spin States
	// ---------------------------------------------------------
	State T0
	{
	    spin(e1) = |0>;
	}
	State T0_U
	{
	    spin(e1) = |0>;
	    spin(N14) = |1>;
	}
	State T0_Z
	{
	    spin(e1) = |0>;
	    spin(N14) = |0>;
	}
	State T0_D
	{
	    spin(e1) = |0>;
	    spin(N14) = |-1>;
	}
	State TP_U
	{
	    spin(e1) = |1>;
	    spin(N14) = |1>;
	}
	State TP_Z
	{
	    spin(e1) = |1>;
	    spin(N14) = |0>;
	}
	State TP_D
	{
	    spin(e1) = |1>;
	    spin(N14) = |-1>;
	}
	State TD_U
	{
	    spin(e1) = |-1>;
	    spin(N14) = |1>;
	}
	State TD_Z
	{
	    spin(e1) = |-1>;
	    spin(N14) = |0>;
	}
	State TD_D
	{
	    spin(e1) = |-1>;
	    spin(N14) = |-1>;
	}
	State Identity
	{
	}
	// ---------------------------------------------------------
	// Transitions
	// ---------------------------------------------------------
	Transition T0URD
	{
	    source = T0_U;
	    targetsystem = GS;
	    targetstate = T0_U;
	    rate = 0.077;
	}
	Transition T0ZRD
	{
	    source = T0_Z;
	    targetsystem = GS;
	    targetstate = T0_Z;
	    rate = 0.077;
	}
	Transition T0DRD
	{
	    source = T0_D;
	    targetsystem = GS;
	    targetstate = T0_D;
	    rate = 0.077;
	}
	Transition TPURD
	{
	    source = TP_U;
	    targetsystem = GS;
	    targetstate = TP_U;
	    rate = 0.077;
	}
	Transition TPZRD
	{
	    source = TP_Z;
	    targetsystem = GS;
	    targetstate = TP_Z;
	    rate = 0.077;
	}
	Transition TPDRD
	{
	    source = TP_D;
	    targetsystem = GS;
	    targetstate = TP_D;
	    rate = 0.077;
	}
	Transition TDURD
	{
	    source = TD_U;
	    targetsystem = GS;
	    targetstate = TD_U;
	    rate = 0.077;
	}
	Transition TDZRD
	{
	    source = TD_Z;
	    targetsystem = GS;
	    targetstate = TD_Z;
	    rate = 0.077;
	}
	Transition TDDRD
	{
	    source = TD_D;
	    targetsystem = GS;
	    targetstate = TD_D;
	    rate = 0.077;
	}
	Transition T0UISC
	{
	    source = T0_U;
	    targetsystem = MS;
	    targetstate = I;
	    rate = 0.001;
	}
	Transition T0ZISC
	{
	    source = T0_Z;
	    targetsystem = MS;
	    targetstate = I;
	    rate = 0.001;
	}
	Transition T0DISC
	{
	    source = T0_D;
	    targetsystem = MS;
	    targetstate = I;
	    rate = 0.001;
	}
	Transition TPUISC
	{
	    source = TP_U;
	    targetsystem = MS;
	    targetstate = I;
	    rate = 0.083;
	}
	Transition TPZISC
	{
	    source = TP_Z;
	    targetsystem = MS;
	    targetstate = I;
	    rate = 0.083;
	}
	Transition TPDISC
	{
	    source = TP_D;
	    targetsystem = MS;
	    targetstate = I;
	    rate = 0.083;
	}
	Transition TDUISC
	{
	    source = TD_U;
	    targetsystem = MS;
	    targetstate = I;
	    rate = 0.083;
	}
	Transition TDZISC
	{
	    source = TD_Z;
	    targetsystem = MS;
	    targetstate = I;
	    rate = 0.083;
	}
	Transition TDDISC
	{
	    source = TD_D;
	    targetsystem = MS;
	    targetstate = I;
	    rate = 0.083;
	}
	// ---------------------------------------------------------
	// SpinSystem Properties
	// ---------------------------------------------------------
	Properties prop
	{
	}
}
SpinSystem MS
{
	// ---------------------------------------------------------
	// Spin States
	// ---------------------------------------------------------
	State I
	{
	}
	// ---------------------------------------------------------
	// Transitions
	// ---------------------------------------------------------
	Transition MSGST0U
	{
	    source = I;
	    targetsystem = GS;
	    targetstate = T0_U;
	    rate = 0.0033;
	}
	Transition MSGST0Z
	{
	    source = I;
	    targetsystem = GS;
	    targetstate = T0_Z;
	    rate = 0.0033;
	}
	Transition MSGST0D
	{
	    source = I;
	    targetsystem = GS;
	    targetstate = T0_D;
	    rate = 0.0033;
	}
	Transition MSGSTPU
	{
	    source = I;
	    targetsystem = GS;
	    targetstate = TP_U;
	    rate = 0.001;
	}
	Transition MSGSTPZ
	{
	    source = I;
	    targetsystem = GS;
	    targetstate = TP_Z;
	    rate = 0.001;
	}
	Transition MSGSTPD
	{
	    source = I;
	    targetsystem = GS;
	    targetstate = TP_D;
	    rate = 0.001;
	}
	Transition MSGSTDP
	{
	    source = I;
	    targetsystem = GS;
	    targetstate = TD_U;
	    rate = 0.001;
	}
	Transition MSGSTDZ
	{
	    source = I;
	    targetsystem = GS;
	    targetstate = TD_Z;
	    rate = 0.001;
	}
	Transition MSGSTDD
	{
	    source = I;
	    targetsystem = GS;
	    targetstate = TD_D;
	    rate = 0.001;
	}
}
Settings
{
	// ---------------------------------------------------------
	// General settings
	// ---------------------------------------------------------
	Settings general
	{
		steps = 1;
	}
	// ---------------------------------------------------------
	// Outputs
	// ---------------------------------------------------------
	Output fieldstrength
	{
		type = length;
		vector = GS.zeeman.field;
	}
	Output E
	{
		type = scalar;
		scalar = GS.strain.ex;
	}
	Output delta_E
	{
		type = scalar;
		scalar = GS.strain_modulated.ex;
	}
	Output D
	{
		type = scalar;
		scalar = GS.strain_modulated.rwdcoeff;
	}
}
Run
{
	Task TE
	{
		type = multistaticss-timeevolution;
		logfile = "PL-Strain-TE-0.log";
		datafile = "PL-Strain-TE-0.dat";
		ReactionOperator = Haberkorn;
		transitionyields = false;
		timestep = 0.1;
		totaltime = 10000;
		minimumtimestep = 0.01;
		maximumtimestep = 20;
		atol = 1e-8;
		rtol = 1e-10;
	}
}