/////////////////////////////////////////////////////////////////////////
// HybridNuclearResonanceSolver (RunSection::General::Resonance)
// ------------------
// First-order electron/core-exact, one-nucleus perturbative resonance kernel.
//
// R2A scope:
//   * exact diagonalization of the supplied electronic/exact-core Hamiltonian;
//   * one perturbative nucleus with an unpolarized reference density;
//   * a SpinAPI-generated hyperfine operator on core x nucleus;
//   * nuclear Zeeman/static nuclear Hamiltonian on the one-nucleus space;
//   * no multi-nuclear convolution and no quadrupole-specific policy yet.
//
// The solver does NOT parse g/A tensors. The full core+nucleus hyperfine matrix
// must be generated by SpinAPI so tensor frames, powder rotations, units and
// prefactors remain owned by SpinAPI.
//
// Molecular Spin Dynamics Software - developed by Claus Nielsen and Luca Gerhards.
// (c) 2026 Quantum Biology and Computational Physics Group.
// See LICENSE.txt for license information.
/////////////////////////////////////////////////////////////////////////
#ifndef MOD_RunSection_General_Resonance_HybridNuclearResonanceSolver
#define MOD_RunSection_General_Resonance_HybridNuclearResonanceSolver

#include "ResonanceFieldJacobian.h"
#include "ResonanceTransitionMoments.h"
#include "ResonanceTypes.h"

#include <armadillo>
#include <cmath>
#include <string>
#include <vector>

namespace RunSection::General::Resonance
{
    struct OneNucleusHybridRequest
    {
        // Matrix representation of H_hf on the ordered product
        //     core Hilbert space x perturbative nucleus Hilbert space.
        arma::cx_mat hyperfineCoreNuclear;

        // One-nucleus Hamiltonian and its field derivative. In R2A this is
        // intended for nuclear Zeeman. R2B may add quadrupole to the static
        // nuclear Hamiltonian without changing the solver algebra.
        arma::cx_mat nuclearHamiltonian;
        arma::sp_cx_mat nuclearDHdB;

        arma::uword nuclearDimension = 0;

        // Nuclear-state overlaps below this weight are numerically irrelevant
        // for the one-nucleus stick list and may be discarded.
        double overlapThreshold = 1.0e-14;

        // R2A can qualify d(omega)/dB only when the projected hyperfine
        // Hamiltonian is independent of field magnitude at fixed orientation.
        // This is true for the intended S=1/2 Zeeman-only validation systems.
        // It is generally false for high-spin systems with ZFS-induced
        // field-dependent core eigenvectors and must remain false there until
        // the finite-difference/response gate is implemented.
        bool fieldIndependentProjection = false;
    };

    class HybridNuclearResonanceSolver
    {
    private:
        static bool PartialCoreExpectation(const arma::cx_mat &operatorCoreNuclear,
            const arma::cx_vec &coreState, arma::uword nuclearDimension,
            arma::cx_mat &out)
        {
            out.reset();
            const arma::uword coreDimension = coreState.n_elem;
            if (coreDimension == 0 || nuclearDimension == 0 ||
                operatorCoreNuclear.n_rows != coreDimension*nuclearDimension ||
                operatorCoreNuclear.n_cols != coreDimension*nuclearDimension)
                return false;

            out.zeros(nuclearDimension,nuclearDimension);

            // SpinSpace embeds operators by successive Kronecker products.
            // R2A therefore requires the perturbative nucleus to be the final
            // factor of the auxiliary core+nucleus SpinSpace. Matrix blocks
            // (i,j) are then nuclearDimension x nuclearDimension.
            for (arma::uword i=0; i<coreDimension; ++i)
            {
                for (arma::uword j=0; j<coreDimension; ++j)
                {
                    const arma::cx_double weight =
                        std::conj(coreState(i))*coreState(j);
                    if (std::abs(weight) == 0.0)
                        continue;

                    const arma::uword r0 = i*nuclearDimension;
                    const arma::uword c0 = j*nuclearDimension;
                    out += weight * operatorCoreNuclear.submat(
                        r0,c0,
                        r0+nuclearDimension-1,
                        c0+nuclearDimension-1);
                }
            }

            // The physical projected Hamiltonian is Hermitian. Remove only
            // roundoff-level anti-Hermitian noise before eig_sym.
            out = 0.5*(out + out.t());
            return out.is_finite();
        }

        struct NuclearManifold
        {
            arma::vec energies;
            arma::cx_mat eigenvectors;
            arma::vec dEdB;
        };

    public:
        static bool GenerateFirstOrder(const arma::sp_cx_mat &coreHamiltonian,
            const arma::cx_mat &coreDensity, const arma::sp_cx_mat &coreDHdB,
            const arma::cx_mat &coreMuX, const arma::cx_mat &coreMuY,
            const OneNucleusHybridRequest &hybrid,
            const SpectrumRequest &request, ResonanceLineSet &lineSet,
            std::string &error)
        {
            error.clear();
            lineSet.lines.clear();
            lineSet.fieldJacobianQualified = hybrid.fieldIndependentProjection;

            const arma::uword coreDimension = coreHamiltonian.n_rows;
            const arma::uword nuclearDimension = hybrid.nuclearDimension;

            if (coreDimension == 0 || coreHamiltonian.n_cols != coreDimension)
            {
                error = "hybrid core Hamiltonian must be non-empty and square";
                return false;
            }
            if (coreDensity.n_rows != coreDimension ||
                coreDensity.n_cols != coreDimension ||
                coreDHdB.n_rows != coreDimension ||
                coreDHdB.n_cols != coreDimension ||
                coreMuX.n_rows != coreDimension ||
                coreMuX.n_cols != coreDimension ||
                coreMuY.n_rows != coreDimension ||
                coreMuY.n_cols != coreDimension)
            {
                error = "hybrid core operator dimensions do not match";
                return false;
            }
            if (nuclearDimension < 2 ||
                hybrid.nuclearHamiltonian.n_rows != nuclearDimension ||
                hybrid.nuclearHamiltonian.n_cols != nuclearDimension ||
                hybrid.nuclearDHdB.n_rows != nuclearDimension ||
                hybrid.nuclearDHdB.n_cols != nuclearDimension ||
                hybrid.hyperfineCoreNuclear.n_rows != coreDimension*nuclearDimension ||
                hybrid.hyperfineCoreNuclear.n_cols != coreDimension*nuclearDimension)
            {
                error = "invalid one-nucleus hybrid dimensions";
                return false;
            }
            if (!coreDensity.is_finite() ||
                !hybrid.nuclearHamiltonian.is_finite() ||
                !hybrid.hyperfineCoreNuclear.is_finite() ||
                !std::isfinite(hybrid.overlapThreshold) ||
                hybrid.overlapThreshold < 0.0 ||
                hybrid.overlapThreshold > 1.0 ||
                request.populationThreshold < 0.0 ||
                request.minimumSlope < 0.0 ||
                request.maximumDBdOmega <= 0.0)
            {
                error = "invalid one-nucleus hybrid numerical input";
                return false;
            }

            arma::vec coreEnergies;
            arma::cx_mat coreEigenvectors;
            if (!arma::eig_sym(coreEnergies,coreEigenvectors,
                    arma::cx_mat(coreHamiltonian)))
            {
                error = "failed to diagonalize hybrid core Hamiltonian";
                return false;
            }

            arma::vec coreDEdB;
            if (!ResonanceFieldJacobian::ResolveDegenerateSubspaces(
                    coreEnergies,coreEigenvectors,coreDHdB,coreDEdB,error))
                return false;

            const arma::cx_mat coreDensityEigen =
                coreEigenvectors.t()*coreDensity*coreEigenvectors;
            const arma::vec corePopulations =
                arma::real(coreDensityEigen.diag());
            if (!corePopulations.is_finite())
            {
                error = "non-finite hybrid core populations";
                return false;
            }

            arma::cx_mat muXEigen,muYEigen;
            if (!ResonanceTransitionMoments::Transform(
                    coreEigenvectors,coreMuX,coreMuY,
                    muXEigen,muYEigen,error))
                return false;

            std::vector<NuclearManifold> nuclear(coreDimension);
            for (arma::uword a=0; a<coreDimension; ++a)
            {
                arma::cx_mat projected;
                if (!PartialCoreExpectation(
                        hybrid.hyperfineCoreNuclear,
                        coreEigenvectors.col(a),
                        nuclearDimension,projected))
                {
                    error = "failed to project the hyperfine operator onto a core state";
                    return false;
                }

                arma::cx_mat effectiveNuclear =
                    hybrid.nuclearHamiltonian + projected;
                effectiveNuclear = 0.5*(effectiveNuclear + effectiveNuclear.t());

                if (!arma::eig_sym(
                        nuclear[a].energies,
                        nuclear[a].eigenvectors,
                        effectiveNuclear))
                {
                    error = "failed to diagonalize an effective nuclear Hamiltonian";
                    return false;
                }

                // In R2A dH_nuc/dB contains the explicit nuclear Zeeman
                // derivative. The derivative of the projected hyperfine term
                // is absent unless the core eigenvectors are field-magnitude
                // independent. The qualification flag above prevents this
                // approximation from silently reaching spectrum evaluation.
                if (!ResonanceFieldJacobian::ResolveDegenerateSubspaces(
                        nuclear[a].energies,
                        nuclear[a].eigenvectors,
                        hybrid.nuclearDHdB,
                        nuclear[a].dEdB,error))
                    return false;
            }

            const double invNuclearDimension =
                1.0/static_cast<double>(nuclearDimension);

            for (arma::uword lower=0; lower<coreDimension; ++lower)
            {
                for (arma::uword upper=lower+1;
                     upper<coreDimension; ++upper)
                {
                    const double corePopulationDifference =
                        corePopulations(lower)-corePopulations(upper);
                    const TransitionMoment coreMoment =
                        ResonanceTransitionMoments::Evaluate(
                            muXEigen,muYEigen,lower,upper);

                    for (arma::uword r=0; r<nuclearDimension; ++r)
                    {
                        for (arma::uword s=0; s<nuclearDimension; ++s)
                        {
                            const arma::cx_double overlap =
                                arma::cdot(
                                    nuclear[upper].eigenvectors.col(s),
                                    nuclear[lower].eigenvectors.col(r));
                            const double overlapWeight = std::norm(overlap);
                            if (overlapWeight < hybrid.overlapThreshold)
                                continue;

                            // R2A assumes an unpolarized perturbative nucleus.
                            const double populationDifference =
                                corePopulationDifference*invNuclearDimension;
                            if (std::abs(populationDifference) <
                                request.populationThreshold)
                                continue;

                            const double signedSlope =
                                (coreDEdB(upper)-coreDEdB(lower)) +
                                (nuclear[upper].dEdB(s)-
                                 nuclear[lower].dEdB(r));
                            const double slope = std::abs(signedSlope);
                            if (!std::isfinite(slope) ||
                                slope < request.minimumSlope)
                                continue;

                            const double dBdOmega = 1.0/slope;
                            if (!std::isfinite(dBdOmega) ||
                                dBdOmega > request.maximumDBdOmega)
                                continue;

                            ResonanceLine line;
                            line.lower = lower;
                            line.upper = upper;
                            line.omega =
                                coreEnergies(upper)-coreEnergies(lower) +
                                nuclear[upper].energies(s)-
                                nuclear[lower].energies(r);
                            line.populationDifference = populationDifference;
                            line.dOmegaDB = slope;
                            line.dBdOmega = dBdOmega;
                            line.moment.x = coreMoment.x*overlapWeight;
                            line.moment.y = coreMoment.y*overlapWeight;
                            line.moment.perpendicular =
                                coreMoment.perpendicular*overlapWeight;
                            lineSet.lines.push_back(line);
                        }
                    }
                }
            }

            return true;
        }
    };
}

#endif
